# serverless.yml
service: serverless-api-demo

plugins:
  - serverless-offline
custom:
  config: ${file(config.${self:provider.stage}.json)}

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1

environment:
  AWS_ACCOUNT_ID: ${self:custom.config.aws.id}

functions:
  app:
    handler: lib/handlers/index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'